MOTIVO-19: Set noindex to be false on default
RemiHin/filament-prefab pull request #23
Opened 2024-12-16 15:08 UTC by DaanTimmerman1

2024-12-18 07:51 UTC, RemiHin requested changes

2024-12-18 07:51 UTC, RemiHin commented on stubs/Modules/Base/App/Traits/Seoable.php
> +                        ->label(__('Don\'t allow index'))
Op deze manier vraag je om een dubbele negatief

Wil je indexeren NIET toestaan? antwoord: Ja 

is verwarrend.

Ik zou het label gelijk laten (Allow index)
en dan een ->dehydrateStateUsing() en ->hydrateStateUsing toevoegen die de boolean om draait.

2025-01-02 09:49 UTC, DaanTimmerman1 commented
Heeft een andere fix nodig, zie FSIN als voorbeeld. Niet mergen.

2025-01-03 13:28 UTC, DaanTimmerman1 commented
Klopt nu wel, mag gemerged worden

2025-01-08 09:03 UTC, rsmit-enrise commented on stubs/Modules/Base/resources/views/components/seo.blade.php
Volgens mij moet je hier juist 'noindex' en 'nofollow' toevoegen wanneer ze true zijn

2025-01-13 14:07 UTC, merged