MOTIVO-28: Add check to not delete a page with a label
RemiHin/filament-prefab pull request #27
Opened 2024-12-30 11:26 UTC by DaanTimmerman1

Maybe we need to show the user what a page with a label is somehow?

2025-01-08 09:55 UTC, rsmit-enrise requested changes
Misschien onnodig, maar zegt het de gebruiker iets wat een label is? Anders gewoon 'U kunt deze pagina niet verwijderen'

2025-01-08 09:55 UTC, rsmit-enrise commented on stubs/Modules/Base/App/Filament/Resources/PageResource.php
Misschien onnodig, maar zegt het de gebruiker iets wat een label is? Anders gewoon 'U kunt deze pagina niet verwijderen'

2025-01-13 12:29 UTC, DaanTimmerman1 commented on stubs/Modules/Base/App/Filament/Resources/PageResource.php
Ik denk dat het de gebruiker niet veel zegt, maar je moet ze denk ik wel een reden geven denk ik?

2025-01-13 13:50 UTC, rsmit-enrise commented on stubs/Modules/Base/App/Filament/Resources/PageResource.php
Vragen Bert of Maikel wel even wat het mooiste is

2025-01-14 09:04 UTC, merged