MOTIVO-25: Add socials module
RemiHin/filament-prefab pull request #29
Opened 2024-12-30 13:37 UTC by DaanTimmerman1

2025-01-08 11:15 UTC, rsmit-enrise requested changes
Naast comment:

1. Command voor socials module moet nog worden toegevoegd in Readme
2. in blade-icons.php moet nog de set worden gedefined voor de social logo's (Weet niet of de logo's zelf ook al in de prefab moeten staan)

2025-01-08 11:15 UTC, rsmit-enrise commented on stubs/Modules/Socials/App/Filament/SocialResource.php
Deze moet aangemaakt worden binnen App\Filament\Resources

2025-01-08 11:15 UTC, rsmit-enrise commented on stubs/Modules/Socials/App/Models/Social.php
> +namespace RemiHin\FilamentPrefabStubs\Modules\Socials\App\Models;
Moet het zijn: `namespace App\Models`

2025-01-08 11:15 UTC, rsmit-enrise commented on stubs/Modules/Socials/database/seeders/SocialSeeder.php
Ik denk dat een seeder projectafhankelijk gemaakt moet worden. Ook hier de namespace

2025-01-13 12:10 UTC, DaanTimmerman1 commented on stubs/Modules/Socials/database/seeders/SocialSeeder.php
Daarom heb ik hem nog redelijk generiek gehouden, dan kan je het zelf gemakkelijk aanvullen :)

2025-01-13 14:50 UTC, merged